id: I6C338BF8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:21:58+00:00'
last_modified: '2022-06-07T15:23:29.275640+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W18127
  title: ཨ་མདོའི་ཤགས་འགྱེད་ལ་གཞས་ལབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4171':
      image_group_id: I1KG14919
      title: ''
      total_pages: 230
      order: 1
      base_file: 4171.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
